services:
  auth-server:
    image: auth-server:v1
    ports:
      - "8081:8081"
    networks:
      - app-network

  webapp:
    image: webapp:v1
    ports:
      - "8080:8080"
    environment:
      - AUTH_URL=http://auth-server:8081
      - RECOMMEND_URL=http://recommend-server:8082
      - SUBMIT_URL=http://user-data:8083
    networks:
      - app-network

  recommend-server:
    image: recommend-server:v1
    ports:
      - "8082:8082"
    networks:
      - app-network

  user-data:
    image: user-data:v1
    ports:
      - "8083:8083"
    environment:
      - AUTH_URL=http://auth-server:8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
