apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    app: {{ .Values.auth.appName }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.image.port }}
  selector:
    matchLabels:
      app: {{ .Values.auth.appName }}