apiVersion: v2
name: AWS-Deployment
description: A Helm chart for deploying a microservice architecture web application on AWS EKS
appVersion: "1.0"
version: 0.1.0
type: application

# dependencies:
#   - name: prometheus
#     version: "13.8.0"
#     repository: "https://prometheus-community.github.io/helm-charts"