deployment:
  localTesting: true
  ingressEnabled: true

frontend:
  logLevel: debug
  replicaCount: 1
  appName: web
  image:
    repository: ishaandatta/aws-deployment
    tag: web
    pullPolicy: IfNotPresent
    port: 8080
  service:
    port: 8080
    nodePort: 30000

authentication:
  logLevel: debug
  replicaCount: 1
  appName: auth
  image:
    repository: ishaandatta/aws-deployment
    tag: auth
    pullPolicy: IfNotPresent
    port: 8081
  service:
    type: ClusterIP
    port: 8081

recommendation:
  logLevel: debug
  replicaCount: 1
  appName: rec
  image:
    repository: ishaandatta/aws-deployment
    tag: rec
    pullPolicy: IfNotPresent
    port: 8082
  service:
    type: ClusterIP
    port: 8082

userdatabase:
  logLevel: debug
  replicaCount: 1
  appName: data
  image:
    repository: ishaandatta/aws-deployment
    local_tag: ldata
    cloud_tag: cdata
    pullPolicy: IfNotPresent
    port: 8083
  service:
    type: ClusterIP
    port: 8083
  env:
    DB_USERNAME: ""
    DB_PASSWORD: ""
    DB_URL: ""

resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: false # change later
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false