rbac: 
  create: false

frontend:
  replicaCount: 1
  appName: web
  image:
    repository: ishaandatta/aws-deployment
    tag: web
    pullPolicy: IfNotPresent
    port: 80
  service:
    type: NodePort #clusterIP
    port: 80 #8080
    nodePort: 8080

auth:
  replicaCount: 1
  appName: auth
  image:
    repository: ishaandatta/aws-deployment
    tag: auth
    pullPolicy: IfNotPresent
    port: 8081
  service:
    type: ClusterIP
    port: 8081

recommend:
  replicaCount: 1
  appName: rec
  image:
    repository: ishaandatta/aws-deployment
    tag: rec
    pullPolicy: IfNotPresent
    port: 8082
  service:
    type: ClusterIP
    port: 8082

userdata:
  replicaCount: 1
  appName: data
  image:
    repository: ishaandatta/aws-deployment
    tag: data
    pullPolicy: IfNotPresent
    port: 8083
  service:
    type: ClusterIP
    port: 8083

prometheus:
  server:
    service:
      type: NodePort

ingress-nginx:
  controller:
    service:
      type: NodePort

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: 127.0.0.1
      paths:
        - path: /
          pathType: ImplementationSpecific
  # tls: []

resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80