apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-database
spec:
  replicas: {{ .Values.userdata.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.userdata.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.userdata.appName }}
    spec:
      containers:
      - name: {{ .Values.userdata.appName }}-{{ randAlpha 5 | lower }}
        image: "{{ .Values.userdata.image.repository }}:{{ .Values.userdata.image.tag }}"
        imagePullPolicy: {{ .Values.userdata.image.pullPolicy }}
        resources: 
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
        ports:
          - containerPort: {{ .Values.userdata.image.port }}
        env:
          - name: PORT 
            value: "{{ .Values.userdata.image.port }}"
          - name: AUTH_URL
            value: "http://authentication:{{ .Values.auth.service.port }}"
          # - name: LOG_LEVEL
          #   valueFrom:
          #     configMapKeyRef:
          #       name: log-config
          #       key: log-level
          # - name: MYSQL_CONNECTION_STRING
          #   valueFrom:
          #     secretKeyRef:
          #       name: mysql-connection-secret
          #       key: connection-string
        livenessProbe:
          httpGet:
            path: /status
            port: {{ .Values.userdata.image.port }}
          initialDelaySeconds: 5
          timeoutSeconds: 1