{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  # namespace: default # change later
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app: {{ .Chart.Name }}
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: frontend
      port:
        number: 80
  rules:
    - host: mylocaltestsite.local
      http:
        paths:
        - path: /auth(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: authentication
              port:
                number: 8081
        - path: /webapp(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: frontend
              port:
                number: 80
        - path: /recommend(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: recommend
              port:
                number: 8082
        - path: /user-data(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: userdata
              port:
                number: 8083
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Values.ingress.name }}
#   namespace: {{ .Values.ingress.namespace }}
#   labels:
#     app: {{ .Chart.Name }}
# spec:
#   rules:
#     {{- range .Values.ingress.rules }}
#     - host: {{ .host }}
#       http:
#         paths:
#           {{- range .http.paths }}
#           - path: {{ .path }}
#             pathType: {{ .pathType }}
#             backend:
#               service:
#                 name: {{ .backend.service.name }}
#                 port:
#                   number: {{ .backend.service.port.number }}
#           {{- end }}
#     {{- end }}
# {{- end }}