rbac: 
  create: false

frontend:
  replicaCount: 1
  appName: web
  image:
    repository: ishaandatta/aws-deployment
    tag: web
    pullPolicy: IfNotPresent
    port: "80"
  service:
    type: NodePort #clusterIP
    port: 80 #8080
    nodePort: 30000

auth:
  replicaCount: 1
  appName: auth
  image:
    repository: ishaandatta/aws-deployment
    tag: auth
    pullPolicy: IfNotPresent
    port: 8081
  service:
    type: ClusterIP
    port: 8081

recommend:
  replicaCount: 1
  appName: rec
  image:
    repository: ishaandatta/aws-deployment
    tag: rec
    pullPolicy: IfNotPresent
    port: 8082
  service:
    type: ClusterIP
    port: 8082

userdata:
  replicaCount: 1
  appName: data
  image:
    repository: ishaandatta/aws-deployment
    tag: data
    pullPolicy: IfNotPresent
    port: 8083
  service:
    type: ClusterIP
    port: 8083

prometheus:
  server:
    service:
      type: NodePort

# server:
#   ## Prometheus server container name
#   name: server

#   service:
#     nodePort: 30001
#     type: NodePort

testing:
  enabled: true

production:
  enabled: false

ingress:
  enabled: true
  name: dev-test-service
  namespace: development
  path: /
  pathType: Prefix
  rules:
    - host: 127.0.0.1
      http:
        paths:
          - path: /wishlist
            pathType: Prefix
            backend:
              service:
                name: wishlist-service
                port:
                  number: 8080
          - path: /products
            pathType: Prefix
            backend:
              service:
                name: wishlist-service
                port:
                  number: 8081
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: wishlist-service
                port:
                  number: 8082

resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: false # change later
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80